### ISSUE TITLE
unicode quotes notdef for postscript

### ISSUE THREAD

**Issue by bbeardsley** [leesavide/abcm2ps#15]
My abc file has unicode apostrophe and quotes in the words but abcm2ps is returning notdef in both ps and eps output.  How do I go about getting it to work with ps/eps?

**Comment by bbeardsley** [comment]
I did a apt-get install libpango1.0-dev and recompiled.  Now the unicode quotes are rendered but in a different font :(

**Comment by bbeardsley** [comment]
%abc-2.1
X:1
T: Test
M: 4/4
L: 1/4
K: C
CC
W:I’ve found
W:I have not found

**Comment by bbeardsley** [comment]
I've found and I have not found lines are in different fonts when pango is enabled.  When it is not enabled, the apostrophe in I've is notdef

**Comment by bbeardsley** [comment]
1st - With pango, 2nd - without.  On the first notice the different fonts being used, on the second the apostrophe is gone (notdef)

![test-with-pango](https://user-images.githubusercontent.com/9709/36926150-7a5d83b4-1e33-11e8-909d-54aef0b94d1c.png)

![test-without-pango](https://user-images.githubusercontent.com/9709/36926152-7a7a4f26-1e33-11e8-8e18-218a0a61098a.png)

**Comment by bbeardsley** [comment]
In the PS if I replace 

/TeXGyreTermes-Regular 16.0 selectfont

with 

16.0 F2

It renders correctly - not sure why it's doing the first...

**Comment by moinejf** [comment]
Without pango (--pango 0 in the command line), you just have to define the missing glyphs with %%glyph:
```
%%glyph 2019 quoteright
```

Otherwise, in my distro (VoidLinux), they removed PS support in pango, so, I cannot fully test your font problem.
But this can be explained by the fact that, when finding a non ASCII character, pango searches a  font in which the character may be rendered. Then, this font is not changed anymore, up to the next line.
In your case, the first searched font would not be the current font, and, so, the font change.

Anyway, unicode rendering with PostScript is a nightmare. That's why I engage people to move to abc2svg.
