### ISSUE TITLE
Missing files for compilation

### ISSUE THREAD

**Issue by RockyRoad29** [leesavide/abcm2ps#3]
Hi leesavide,

A big thanks for maintaining git versionning for abc tools.

However I was not able to compile abcm2ps from the cloned repo.

Comparing with the contents of [abcm2ps-8.13.1.tar.gz](http://moinejf.free.fr/abcm2ps-8.13.1.tar.gz), there where two missing files:
  - `Makefile.in`
  - `config.h.in`

Actually they were excluded in your `.gitignore` file (a bit bulky to my taste if I may say).
Also maybe `Makefile` should not be versionned since it is generated, but it is included in official source, so I left it in.

Here is my proposed patch (git diff):
[compilable.patch.txt](https://github.com/leesavide/abcm2ps/files/659354/compilable.patch.txt)

Hope this helps

**Comment by lewdlime** [comment]
Thank you for telling me about this: I only just realized that the `.gitignore` file had them ignored. I've re-pushed the latest version with the missing `Makefile.in` &` config.in` files, but I do not have enough mastery over Git to fix the issue with past commits. :frowning_face:

The main focus on this repository is to show changes in code between versions, rather than be an active repository that would try to replace Jean-François Moine's [own website](http://moinejf.free.fr/). As such, anytime he updates his code from his website, I copy the files from the new archive, commit & tag them, then push, since I do not take any credit for writing the code, which is why the `Makefile` is left in.
