### ISSUE TITLE
is it possible to automatically wrap text?

### ISSUE THREAD

**Issue by olets** [leesavide/abcm2ps#33]
Is there a way to have text (in `W:`, or `%%begintext ... %%endtext`, or something else) automatically wrap to multiple lines, following the same width as `staffwidth`?

**Comment by moinejf** [comment]
I don't see what you want exactly.   
```%%begintext``` accepts an option which can be ```fill``` or ```justify``` in which case automatic wrap occurs.   
There is no such option for ```W:```.   
Otherwise, ```%%staffwidth``` is an other way to set the left and right margins. So, if you want the width of the text lines to be the same as the staff width, better use ```%%leftmargin``` and ```%%rightmargin```.

**Comment by olets** [comment]
Aha, thanks I didn't know about those options. `justify` meets my needs, so now I'm using `begintext` + `textoption 1`
