### ISSUE TITLE
Compile abcm2ps using Visual Studio 2015 

### ISSUE THREAD

**Issue by ciacob** [leesavide/abcm2ps#4]
Hello,

Not exactly an issue, but I am trying to compile abcm2ps using Visual Studio 2015 (the free, Community Edition), and I receive hundreds of errors. Have you tried doing that? I don't even know where to start, to fix it.

Thanks,
Claudius

**Comment by lewdlime** [comment]
You're receiving errors because abcm2ps is normally compiled through a Unix or Linux based OS, using the GNU GCC compiler. For you to compile abcm2ps on Windows, you'd either have to use [Cygwin](http://cygwin.com) or [MinGW](http://www.mingw.org), and compile using the Makefile from the command line.

Currently, Microsoft's C/C++ compiler toolset isn't usually able to handle UNIX/Linux based Makefile projects, at least not without adapting the source code or build system. On the other hand, lately they've begun to remedy this by beginning to make Windows incorporate UNIX/Linux tools & commands, including the Clang compiler. But for now, you're best off by using one of the 2 compiler suites I mentioned earlier.

If these don't work for you, there are Windows builds of the tools available from the [ABC Plus](http://abcplus.sourceforge.net/) project, as well as Windows builds of abcMIDI.

**Comment by ciacob** [comment]
Thank you for your quick answer. Will the cross-compiled binaries run smoothly on any Windows version (in the range of WinXP - Win10)?

I know there are binaries available for download, but I want to alter the program (I want to use the ABC "Annotation" feature for setting the IDs of the generated SVG elements).

**Comment by lewdlime** [comment]
The binaries work on any Windows OS; I can confirm this having run the programs on Windows XP, 7, 8, 8.1, and 10.

**Comment by ciacob** [comment]
Thanks for the info!

**Comment by lewdlime** [comment]
Don't mention it, anytime :)
