### ISSUE TITLE
Words other than trailing  "The" get moved to front of title

### ISSUE THREAD

**Issue by rcedward** [leesavide/abcm2ps#78]
Titles such as "Kenny Gillies of Portnalong, Skye" get rendered as "Skye Kenny Gillies of Portnalong"

Expected: title gets rendered unmodified

Fix: In subs.c:trim_title, check for first letter after comma to be 'T', else do not move word to front

**Comment by moinejf** [comment]
Your fix does not work with titles as
T:fine journey, A
T:hübsche Frau, Die
T:danse des canards, La

It is simpler to set:

`%%titletrim 0`

**Comment by rcedward** [comment]
Fair enough, but the comment in the code should be changed:
"/* -- move trailing "The" to front, set to uppercase letters or add xref -- */"

Should read more like,
/* -- move trailing words such as "A" and "The" to front, set to uppercase letters or add xref -- */

The comment suggests the intent is to move _only_ the word "The", but that's not what the code does.

To be honest, to me altering the title at all from what is in the .abc file is unexpected behavior. Perhaps logic should be reversed and the title should remain unaltered unless the user specifies
 `%%titletrim 1`

Cheers!

**Comment by moinejf** [comment]
You are right, but:
- the first code of the function was just moving 'The'. Sorry for I forgot to update the comment.
- the default value of %%titletrim has been set to true since its development before July 2006. I cannot change it now.
- you may change its value in your default.abc.
I will try to change this default value in abc2svg...

**Comment by rcedward** [comment]
Sounds good. Thanks!
